# Generated by Django 3.0.2 on 2020-02-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='Anime_view',
            field=models.IntegerField(default=0),
        ),
    ]
