# Generated by Django 3.1.6 on 2021-02-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_anime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='Anime_Category',
            field=models.CharField(choices=[('C', 'Comedy'), ('A', 'Adventure'), ('D', 'Horror'), ('R', 'Romance')], max_length=1),
        ),
    ]
