# Generated by Django 2.2 on 2021-04-30 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='prediction',
            field=models.CharField(default='NO Prediction', max_length=20),
        ),
    ]
